language: go
sudo: false

matrix:
  include:
    - go: 1.5
    - go: 1.6
    - go: 1.7

before_install:
  - go get golang.org/x/tools/cmd/cover

install:
  - mkdir -p $HOME/gopath/src/gopkg.in/speijnik
  - mv $HOME/gopath/src/github.com/speijnik/logrus-modular $HOME/gopath/src/gopkg.in/speijnik/logrus-modular.v1
  - cd $HOME/gopath/src/gopkg.in/speijnik/logrus-modular.v1

script:
  - go get -t -v ./...
  - diff -u <(echo -n) <(gofmt -d .)
  - go tool vet .
  - go test -v -coverprofile=coverage.txt -covermode=atomic
  - go run ./examples/simple/simple.go

after_success:
  - bash <(curl -s https://codecov.io/bash)
